export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";
export const AUTENTICAR_USUARIO = "AUTENTICAR_USUARIO";
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";
export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO";
export const CREAR_ENLACE = "CREAR_ENLACE";
export const CARGANDO = "CARGANDO";
export const LIMPIAR_STATE = "LIMPIAR_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS";